# Add application configuration variables here, as shown below.

PAYPAL_URL: ""
PAYPAL_PDT_AT: ""
PAYPAL_ACCOUNT: ""

development:
  DB_NAME: ''
  DB_USER: ''
  DB_PASS: ''

production:
  DB_NAME: ''
  DB_USER: ''
  DB_PASS: ''
  MAIL_HOST: ''
  SECRET_TOKEN: ''

test:
  DB_NAME: ''
  DB_USER: ''
  DB_PASS: ''
  FAKE_IP: ''
